version: "3.9"

services: 
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
  
  # cache:
  #   image: memcached
  #   command:
  #     -'m 1024'
  #     -'c 1024'
  #     -'t 2'
  #   ports:
  #     - "11211:11211"